# Generated by Django 4.2.16 on 2024-12-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AHVP_app", "0002_mrisonuc_remove_hasta_egitim_durumu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="hasta_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
