# Generated by Django 5.1.2 on 2025-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0004_rename_ravlt_forgetting_muayene_ravlt_forgetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrisonuc',
            name='entorhinal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrisonuc',
            name='fusiform',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrisonuc',
            name='hippocampus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrisonuc',
            name='mid_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrisonuc',
            name='ventricles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrisonuc',
            name='whole_brain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
