# Generated by Django 4.2.16 on 2024-10-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hasta",
            fields=[
                (
                    "hasta_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("isim", models.CharField(max_length=100)),
                ("soyisim", models.CharField(max_length=100)),
                ("cinsiyet", models.CharField(max_length=10)),
                ("yas", models.IntegerField()),
                ("sehir", models.CharField(max_length=100)),
                ("medeni_durum", models.CharField(max_length=100)),
                ("egitim_durumu", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Muayene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sifrelenmis_tarih", models.CharField(max_length=100)),
                (
                    "hasta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AHVP_app.hasta"
                    ),
                ),
            ],
        ),
    ]
