# Generated by Django 4.2.16 on 2024-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayene",
            name="sifrelenmis_tarih",
            field=models.CharField(max_length=255),
        ),
    ]
