# Generated by Django 4.2.16 on 2024-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0002_alter_muayene_sifrelenmis_tarih"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="cinsiyet",
            field=models.CharField(
                choices=[("kadın", "Kadın"), ("erkek", "Erkek")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="hasta",
            name="medeni_durum",
            field=models.CharField(
                choices=[
                    ("evli", "Evli"),
                    ("bekar", "Bekar"),
                    ("boşanmış", "Boşanmış"),
                ],
                max_length=10,
            ),
        ),
    ]
