# Generated by Django 4.2.16 on 2024-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0003_alter_hasta_cinsiyet_alter_hasta_medeni_durum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="medeni_durum",
            field=models.CharField(
                choices=[
                    ("evli", "Evli"),
                    ("bekar", "Bekar"),
                    ("boşanmış", "Boşanmış"),
                ],
                max_length=100,
            ),
        ),
    ]
