# Generated by Django 4.2.16 on 2024-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0005_alter_hasta_sehir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="egitim_durumu",
            field=models.CharField(
                choices=[("lise", "Lise"), ("lisans", "Lisans"), ("yok", "Yok")],
                max_length=100,
            ),
        ),
    ]
