# Generated by Django 5.1.2 on 2024-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0006_alter_hasta_egitim_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='muayene',
            name='denge_bozuklugu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='ense_sertligi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='kranial_sinir_bulgulari',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='motor_duygusal_bulgular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='parkinsonizm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='patolojik_refleks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muayene',
            name='serebellar_bulgular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='sehir',
            field=models.CharField(choices=[('adana', 'Adana'), ('ankara', 'Ankara'), ('istanbul', 'İstanbul'), ('izmir', 'İzmir'), ('antalya', 'Antalya')], max_length=100),
        ),
    ]
