# Generated by Django 5.1.2 on 2024-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0007_muayene_denge_bozuklugu_muayene_ense_sertligi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muayene',
            name='acer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='ast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='bt_sonucu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='bun',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='eeg_sonucu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='ek_testler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='ekg_sonucu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='eritrosit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='kreatinin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='ldh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='mmse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='moca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='mri_freesurfer',
            field=models.FileField(blank=True, null=True, upload_to='mri/'),
        ),
        migrations.AddField(
            model_name='muayene',
            name='mri_notlari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='mri_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pa_akciger_grafisi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='pet9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='sedim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='tam_kan_hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='tam_kan_lym',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='tam_kan_neu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='tam_kan_plt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='uric_acid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='vitamin_b12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='vldrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
