# Generated by Django 5.1.2 on 2024-10-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0009_alter_hasta_sehir'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSurferSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('brain_seg_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brain_seg_vol_not_vent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ventricle_choroid_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lh_cortex_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rh_cortex_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cortex_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('muayene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AHVP_app.muayene')),
            ],
        ),
    ]
