# Generated by Django 4.2.16 on 2024-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0011_freesurfersonuc_brain_seg_vol_to_etiv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="muayene",
            name="ekg_sonucu",
        ),
        migrations.RemoveField(
            model_name="muayene",
            name="moca",
        ),
        migrations.AddField(
            model_name="muayene",
            name="eeg_file",
            field=models.FileField(blank=True, null=True, upload_to="mri/"),
        ),
        migrations.AddField(
            model_name="muayene",
            name="npt",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
