# Generated by Django 4.2.16 on 2024-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0012_remove_muayene_ekg_sonucu_remove_muayene_moca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="muayene",
            name="amiloid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="muayene",
            name="tau",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
