# Generated by Django 4.2.16 on 2024-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AHVP_app", "0013_muayene_amiloid_muayene_tau"),
    ]

    operations = [
        migrations.AddField(
            model_name="muayene",
            name="beck_anksiyete",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="beck_depresyon",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="geriatrik_depresyon",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_dikkat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_hatirlama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_kayithafizasi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_lisan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_yer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muayene",
            name="mmse_zaman",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
