# Generated by Django 5.1.2 on 2024-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0015_hasta_meslek'),
    ]

    operations = [
        migrations.AddField(
            model_name='muayene',
            name='glukoz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='muayene',
            name='tiroid_fonksiyon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
