# Generated by Django 5.1.2 on 2024-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AHVP_app', '0016_muayene_glukoz_muayene_tiroid_fonksiyon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasta',
            old_name='hasta_id',
            new_name='hasta_id',
        ),
    ]
